version: '3.0'
services:

    # gateway:
    #   image: nginx:1.17.6
    #   ports:
    #     - 80:80/tcp
    #     - 443:443/tcp
    #     - 3305:3305/tcp
    #     - 8080:8080/tcp
    #   volumes:
    #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     - ./nginx/log:/var/log/nginx
    #     - ./certs:/opt/certs
    #   stdin_open: true
    #   depends_on:
    #     - application
    #   tty: true
    #   restart: always

    application:
        image: siltu/email-ui:2.0
        ports:
          - 8001:8001/tcp
        # privileged: true
        # volumes:
        #     - '.:/var/www/html'
        environment:
          DB_HOST: pxc
    pxc:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: application
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      restart: always
      volumes:
        - /opt/components/controller/mysql:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.2
      links:
        - pxc:db
      ports:
        - 3307:80/tcp
      environment:
        PMA_HOST: pxc
      restart: always
